spring.datasource.url=jdbc:postgresql://localhost:5432/moviesdb
spring.datasource.username=postgres
spring.datasource.password=STUDENT
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081